set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_EXTENSIONS   OFF)

# or mtune cortex-a75 / cortex-a76
set(FLAGS_ARCH  "-march=armv8.2-a -mtune=generic-armv8.2-a")
set(FLAGS_GEN   "-ffunction-sections -fdata-sections")
set(FLAGS_WARN  "-Wall -Werror=return-type")

set(CMAKE_ASM_FLAGS                "${FLAGS_ARCH} ${FLAGS_GEN} ${FLAGS_WARN} -Wa,--warn -x assembler-with-cpp" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS_DEBUG           "-O0 -g3" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS_RELEASE         "-O2"     CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS_RELWITHDEBINFO  "-O2 -g3" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS_MINSIZEREL      "-Os"     CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS                   "${FLAGS_ARCH} ${FLAGS_GEN} ${FLAGS_WARN}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_DEBUG             "-O0 -g3" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE           "-O2"     CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELWITHDEBINFO    "-O2 -g3" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_MINSIZEREL        "-Os"     CACHE STRING "" FORCE)

set(CMAKE_CXX_FLAGS                 "${FLAGS_ARCH} ${FLAGS_GEN} ${FLAGS_WARN}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_DEBUG           "-O0 -g3" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELEASE         "-O2"     CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO  "-O2 -g3" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_MINSIZEREL      "-Os"     CACHE STRING "" FORCE)
