#!/bin/bash

trap 'exit -1' err

if [[ $(id -u opaleye &>/dev/null) -ne 0 ]]; then
	# create a no-login system user with a home dir
	useradd opaleye -s /usr/sbin/nologin --create-home --system -U -G cdrom,audio,dip,video,plugdev,i2c,gdm,lightdm,weston-launch,gpio
fi

if [[ -f /etc/nginx/sites-enabled/opaleye  ]]; then
	exit -1
fi

if [[ -f /etc/nginx/sites-enabled/default  ]]; then
	rm /etc/nginx/sites-enabled/default
fi

ln -s /etc/nginx/sites-available/opaleye /etc/nginx/sites-enabled/opaleye 

if [[ $(systemctl is-active --quiet nginx) ]]; then
	service nginx reload
fi

mkdir -p /opt/suburbanmarine/opaleye/record/video
mkdir -p /opt/suburbanmarine/opaleye/record/image
mkdir -p /opt/suburbanmarine/opaleye/log

# systemctl enable ptp4l.service 
systemctl enable opaleye.service 

# systemctl start ptp4l.service 
systemctl start opaleye.service 

exit 0
