#!/bin/bash

trap 'exit -1' err

if [[ -f /etc/nginx/sites-enabled/opaleye ]]; then
	rm /etc/nginx/sites-enabled/opaleye
fi

if [[ $(systemctl is-active --quiet nginx) ]]; then
	service nginx reload
fi

exit 0
